### ISSUE TITLE
"Command not found" and "Missing semicolon"

### ISSUE THREAD

**Issue by KonradHoeffner** [originjs/webpack-to-vite#76]
### Versions

- webpack-to-vite: 1.0.1
- node: 17.1.0

### Reproduction

GitHub repository at this commit: <https://github.com/snikproject/quiz/commit/60ea114f0368f7400bb06f7f93d9cac52586e17e>

### Steps to reproduce

```
$ npx @originjs/webpack-to-vite -t webpack .
sh: line 1: webpack-to-vite: command not found
$ sudo npm install @originjs/webpack-to-vite -g
$ webpack-to-vite -t webpack .
******************* Webpack to Vite *******************
Project path: .
progress [██████████████████░░░░░░░░░░░░░░░░░░░░░░] 44% | AST Parsing: /home/konrad/projekte/snik/snik-quiz/src/componSyntaxError: Missing semicolon. (1:63)
    at Object._raise (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:541:17)
    at Object.raiseWithData (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:495:17)
    at Object.semicolon (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:3550:10)
    at Object.parseExpressionStatement (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13899:10)
    at Object.parseStatementContent (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13490:19)
    at Object.parseStatement (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13352:17)
    at Object.parseLabeledStatement (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13891:22)
    at Object.parseStatementContent (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13488:19)
    at Object.parseStatement (/usr/lib/node_modules/@originjs/webpack-to-vite/node_modules/@babel/parser/lib/index.js:13352:17) {
  loc: Position { line: 1, column: 63 },
  pos: 63,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingSemicolon'
}
Conversion failed.

```

### What is Expected?
- it should work with npx
- it should transform my project

### What is actually happening?
- it does not work with npx
- it fails because of a missing semicolon in the originjs code (?)

**Comment by Chieffo2021** [comment]
> it should work with npx

I clone your repo and reset to your commit, then I tried to use reproduce with npx, it does reproduce. I google it and found a way to resolve, which is check the $PATH with “echo $PATH”, see [here](https://osxdaily.com/2018/05/24/command-not-found-mac-terminal-error-fix/). After that, I cannot reproduce the problem anymore. So I guess it is the way to solve the problem.

my logs here:
```
Chieffo@Chieffos-MBP Desktop % git clone https://github.com/snikproject/quiz.git
Cloning into 'quiz'...
remote: Enumerating objects: 383, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 383 (delta 85), reused 100 (delta 58), pack-reused 239
Receiving objects: 100% (383/383), 983.45 KiB | 493.00 KiB/s, done.
Resolving deltas: 100% (194/194), done.
Chieffo@Chieffos-MBP Desktop % git reset 60ea114 --hard
fatal: not a git repository (or any of the parent directories): .git
Chieffo@Chieffos-MBP Desktop % cd quiz 
Chieffo@Chieffos-MBP quiz % git reset 60ea114 --hard
HEAD is now at 60ea114 Interpret MAX_QUESTION_COUNT value 0 as unlimited.
Chieffo@Chieffos-MBP quiz % npx @originjs/webpack-to-vite . -t webpack
******************* Webpack to Vite *******************
Project path: .
SyntaxError: Missing semicolon. (1:63)
    at Object._raise (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:541:17)ject-data.js | 26/52
    at Object.raiseWithData (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:495:17)
    at Object.semicolon (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:3550:10)
    at Object.parseExpressionStatement (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13899:10)
    at Object.parseStatementContent (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13490:19)
    at Object.parseStatement (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13352:17)
    at Object.parseLabeledStatement (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13891:22)
    at Object.parseStatementContent (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13488:19)
    at Object.parseStatement (/Users/Chieffo/.npm/_npx/b44295a6bb13d916/node_modules/@babel/parser/lib/index.js:13352:17) {
  loc: Position { line: 1, column: 63 },
  pos: 63,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingSemicolon'
}
Conversion failed.
```
> it should transform my project

I checked your file and found that the file `src/data/subject-data.js` is not a standard js file, it might be a jsx file I think? We cannot parse its content (AST parser throw error), I personally recommand that you rename the file extension to `.jsx` as [Evan You said](https://twitter.com/youyuxi/status/1362050255009816577).

**Comment by Chieffo2021** [comment]
You can now successfully convert your project, as the tool will skip the parsing error files and log the error files that you need to convert manually.

Success log:
```
$ npx @originjs/webpack-to-vite . -t webpack
npm WARN exec The following package was not found and will be installed: @originjs/webpack-to-vite
******************* Webpack to Vite *******************
Project path: .


Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
AST parsing and transformation file failed, filePath: D:/project/github-project/quiz/src/data/subject-data.js
 SyntaxError: Missing semicolon. (1:63)
    at Object._raise (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:495:17)
    at Object.semicolon (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:3550:10)
    at Object.parseExpressionStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13899:10)
    at Object.parseStatementContent (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13490:19)
    at Object.parseStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13352:17)
    at Object.parseLabeledStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13891:22)
    at Object.parseStatementContent (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13488:19)
    at Object.parseStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13352:17) {
  loc: Position { line: 1, column: 63 },
  pos: 63,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingSemicolon'
}
skip parsing the error file...

Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
AST parsing file failed, filePath: D:/project/github-project/quiz/src/data/subject-data.js
 SyntaxError: Missing semicolon. (1:63)
    at Object._raise (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:495:17)
    at Object.semicolon (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:3550:10)
    at Object.parseExpressionStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13899:10)
    at Object.parseExpressionStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:5333:18)
    at Object.parseStatementContent (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13490:19)
    at Object.parseStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13352:17)
    at Object.parseStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:5307:24)
    at Object.parseLabeledStatement (C:\Users\test\AppData\Local\npm-cache\_npx\b44295a6bb13d916\node_modules\@babel\parser\lib\index.js:13891:22) {
  loc: Position { line: 1, column: 63 },
  pos: 63,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingSemicolon'
}
skip parsing the error file...

Failed to parse webpack config from default file path: D:\project\github-project\quiz\webpack\webpack.dev.conf.js.
Note: webpack conversion is based on `webpack.config.js` or `webpack.base.js/webpack.dev.js/webpack.prod.js` or `webpack.build.js/webpack.production.js`, map configuration to `vite.config.js`.
If you are not using configuration files above, you need to convert configurations manually.
Using default webpack config: {}.
conversion items successful converted:
╔════════╤═══════════════════════╤══════════════════╗
║ Number │ Conversion item       │ Conversion count ║
╟────────┼───────────────────────┼──────────────────╢
║  B01   │ add package.json      │        1         ║
║  B04   │ required plugins      │        1         ║
║  W01   │ build input options   │        1         ║
║  W02   │ outDir options        │        1         ║
║  W03   │ resolve.alias options │        1         ║
║  W05   │ define options        │        1         ║
║  B03   │ add vite.config.js    │        1         ║
║  B02   │ add index.html        │        1         ║
╚════════╧═══════════════════════╧══════════════════╝

Conversion finished in 4053ms.
The report output path is ./conversion.log
************************ Done ! ************************
Now please run:

npm install
npm run serve-vite

```

**Comment by KonradHoeffner** [comment]
Thanks for the fix!
